dt: 0.01

desired_speed: 1.0

waypoints:
    - [   0,   0, -20]
    - [   8,   0, -20]
    - [  16,  12, -24]
    - [  20,  12, -27]
    - [  25,  16, -25]
    - [  25,  20, -25]
    - [  30,  40, -25]
    - [  36,  45, -25]
    - [  60,  70, -45]
    - [ 105,  56, -60]
    - [ 100, -20, -60]
    - [ 100, -20, -59]