dt: 0.001

desired_speed: 0.1

waypoints:
    - [    0,    0,   -1]
    - [    8,    0,   -1]
    - [   10,    2, -1.5]
    - [    5,    5, -1.5]
    - [   -5,   -2,   -1]
    - [   -7,    0, -0.5]
    - [   -5,    2, -0.5]
    - [    5,   -2,   -1]
    - [    4,   -4,   -1]
    - [    0,   -4,   -1]
    - [   -2,   -2,   -1]
    - [    0,    0,   -1]