controller_type: "mimo_nl_pid"

Kp: [  97,   97,   97,    8,    8,    8]
Ki: [   5,    5,    5,    2,    2,    2]
Kd: [  26,   26,   26,    2,    2,    2]

acc_fb_gain: 0

lower_limit: -1
upper_limit: 1