controller_type: "mimo_nl_pid"

Kp: [   80,   80,   80,   10,   10,   10]
Ki: [ 4.75, 4.75, 4.75,    2,    2,    2]
Kd: [ 20.6, 20.6, 20.6,    3,    3,    3]

acc_fb_gain: 0

lower_limit: -1
upper_limit: 1